name: FlashTrade Leaderboard Snapshot

on:
  schedule:
    - cron: "0 6 * * *"   # 15:00 JST
  workflow_dispatch:

permissions:
  contents: write   # ← data/last.json をコミットするため

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Pin npm registry
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fund false
          npm config set audit false

      - name: Install dependencies (Playwright)
        run: |
          npm init -y
          npm install --no-audit --no-fund playwright@^1.48.0

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Generate card image
        run: node snapshot.js

      # data/last.json をコミット（次回の前日比較に使う）
      - name: Commit daily data
        run: |
          if [ -n "$(git status --porcelain data/last.json)" ]; then
            git config user.name  "gh-actions"
            git config user.email "actions@github.com"
            git add data/last.json
            git commit -m "chore: update daily snapshot data"
            git push
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard_card
          path: |
            leaderboard_card.png
            leaderboard_rows.json
